### ISSUE TITLE
TypeError: Tag: diffgram invalid (type not found)

### ISSUE THREAD

**Issue by edsnowden** [pysimplesoap/pysimplesoap#67]
Using Python 2.7 and pysimplesoap 1.16, the following test program:

```python
from pysimplesoap.client import SoapClient
client = SoapClient(wsdl='http://www.boosey.com/webservices/composer_Info.asmx?WSDL',trace=False)
response = client.getComposerPerformances(ComposerID=2770, userName='', password='')
```

fails with the following exception trace:

```python
Traceback (most recent call last):
  File "tst.py", line 3, in <module>
    response = client.getComposerPerformances(ComposerID=2770, userName='', password='')
  File "/var/britten/brittenweb/datafeeds/venv/lib/python2.7/site-packages/pysimplesoap/client.py", line 181, in <lambda>
    return lambda *args, **kwargs: self.wsdl_call(attr, *args, **kwargs)
  File "/var/britten/brittenweb/datafeeds/venv/lib/python2.7/site-packages/pysimplesoap/client.py", line 346, in wsdl_call
    return self.wsdl_call_with_args(method, args, kwargs)
  File "/var/britten/brittenweb/datafeeds/venv/lib/python2.7/site-packages/pysimplesoap/client.py", line 372, in wsdl_call_with_args
    resp = response('Body', ns=soap_uri).children().unmarshall(output)
  File "/var/britten/brittenweb/datafeeds/venv/lib/python2.7/site-packages/pysimplesoap/simplexml.py", line 433, in unmarshall
    value = children and children.unmarshall(fn, strict)
  File "/var/britten/brittenweb/datafeeds/venv/lib/python2.7/site-packages/pysimplesoap/simplexml.py", line 433, in unmarshall
    value = children and children.unmarshall(fn, strict)
  File "/var/britten/brittenweb/datafeeds/venv/lib/python2.7/site-packages/pysimplesoap/simplexml.py", line 380, in unmarshall
    raise TypeError("Tag: %s invalid (type not found)" % (name,))
TypeError: Tag: diffgram invalid (type not found)
```

The WSDL is here: http://www.boosey.com/webservices/composer_Info.asmx?WSDL

Using this online tester: http://wsdlbrowser.com

I can see that the XML response for the SOAP call is:

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <getComposerRecordingsResponse
            xmlns="http://www.boosey.com/webservices/composer_Info.asmx">
            <getComposerRecordingsResult>
                <xs:schema id="Recordings"
                    xmlns=""
                    xmlns:xs="http://www.w3.org/2001/XMLSchema"
                    xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
                    <xs:element name="Recordings" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
                        <xs:complexType>
                            <xs:choice minOccurs="0" maxOccurs="unbounded">
                                <xs:element name="Recording">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="ComposerID" type="xs:int" minOccurs="0" />
                                            <xs:element name="LastName" type="xs:string" minOccurs="0" />
                                            <xs:element name="FirstName" type="xs:string" minOccurs="0" />
                                            <xs:element name="RecordingID" type="xs:int" minOccurs="0" />
                                            <xs:element name="Title" type="xs:string" minOccurs="0" />
                                            <xs:element name="SnapshotMenu" type="xs:boolean" minOccurs="0" />
                                            <xs:element name="NewRecording" type="xs:boolean" minOccurs="0" />
                                            <xs:element name="RecordingID1" type="xs:int" minOccurs="0" />
                                            <xs:element name="RecordingText" type="xs:string" minOccurs="0" />
                                            <xs:element name="PhotoName" type="xs:string" minOccurs="0" />
                                            <xs:element name="RecordingOnline" type="xs:boolean" minOccurs="0" />
                                            <xs:element name="WhatsNew" type="xs:boolean" minOccurs="0" />
                                            <xs:element name="RecordingQuote" type="xs:string" minOccurs="0" />
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:choice>
                        </xs:complexType>
                    </xs:element>
                </xs:schema>
                <diffgr:diffgram
                    xmlns:msdata="urn:schemas-microsoft-com:xml-msdata"
                    xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1" />
                </getComposerRecordingsResult>
            </getComposerRecordingsResponse>
        </soap:Body>
    </soap:Envelope>
```

The diffgram tag is visible towards the end.

**Comment by edsnowden** [comment]
Reverting to pysimplesoap-1.05a resolves this.

**Comment by edsnowden** [comment]
Sorry - didn't mean to close the issue by commenting.

**Comment by kramer65** [comment]
@edsnowden (nice name btw), since I'm also facing an issue with a `type not found` error I tried your tip of downgrading to version 1.05a, but unfortunately I now have a problem with authentication. 
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "kik_test.py", line 14, in getKadastraalBerichtObject
    client = SoapClient(wsdl='http://www1.kadaster.nl/1/schemas/kik-inzage/20141101/verzoekTotInformatie-2.1.wsdl', username='xxx', password='xxx', trace=True)
TypeError: __init__() got an unexpected keyword argument 'username'
```
Any idea how I can authenticate with a username and password on version 1.05a?

**Comment by edsnowden** [comment]
I don't really know anything about pysimplesoap. However, if your site is using HTTP Basic Authentication, you might be able to wedge the username and password into the URL:

http://xxx:xxx@www1.kadaster.nl/...

However, that's the URL of the WSDL, whereas the URL of the service is something else. Maybe pysimplesoap will propagate the credentials, who knows! It might be easier to make 1.16 understand the diffgram tag, the pysimplesoap client.py doesn't seem to be a lot of code.

**Comment by edsnowden** [comment]
(If it does work, remember that you're sending the credentials over HTTP, i.e. unencrypted. So maybe switch to HTTPS for the WSDL.)

**Comment by alacret** [comment]
This is not working with version 1.05 either
